import {
  DocumentoFactura,
  DocumentoFacturaDetalleRespuesta,
} from '@interfaces/facturas.interface';

const fechaActual = new Date();
const fullAnio = fechaActual.getFullYear();
const mes = fechaActual.getMonth() + 1;

const fecha = `${fullAnio}-${mes.toString().padStart(2, '0')}-${fechaActual
  .getDate()
  .toString()
  .padStart(2, '0')}`;

export const facturaInit: DocumentoFactura = {
  id: 0,
  contenedor: 0,
  numero: undefined,
  fecha: fecha,
  fecha_vence: fecha,
  fecha_hasta: undefined,
  impuesto_operado: 0,
  contacto_id: 1,
  contacto_numero_identificacion: '22222222222222222222222222222222222222',
  contacto_nombre_corto: 'Consumidor final',
  descuento: 0,
  base_impuesto: 0,
  subtotal: 0,
  afectado: 0,
  pendiente: 0,
  impuesto: 0,
  total: 0,
  devengado: 0,
  deduccion: 0,
  base_cotizacion: 0,
  base_prestacion: 0,
  salario: 0,
  estado_aprobado: false,
  documento_tipo_id: 0,
  metodo_pago: 0,
  metodo_pago_id: 0,
  metodo_pago_nombre: '',
  forma_pago_id: 0,
  forma_pago_nombre: '',
  estado_anulado: false,
  comentario: undefined,
  estado_electronico: false,
  estado_electronico_enviado: false,
  estado_electronico_notificado: false,
  soporte: undefined,
  orden_compra: undefined,
  plazo_pago: 0,
  plazo_pago_id: 0,
  plazo_pago_nombre: '',
  documento_referencia_id: undefined,
  documento_referencia_numero: '',
  cue: undefined,
  electronico_id: undefined,
  asesor: undefined,
  asesor_nombre_corto: undefined,
  sede: undefined,
  sede_nombre: undefined,
  programacion_detalle_id: undefined,
  contrato_id: undefined,
  detalles: [],
  pagos: [],
  referencia_cue: null,
  referencia_numero: 0,
  referencia_prefijo: null,
  grupo_contabilidad_id: 0,
  almacen: 1,
  almacen_id: 0,
  almacen_nombre: '',
  nombre: 'Factura',
  uuid: '',
};

export const documentoFacturaDetalleInit: DocumentoFacturaDetalleRespuesta = {
  id: 0,
  documento_id: 0,
  item: 0,
  item_nombre: '',
  cuenta: undefined,
  cuenta_codigo: '',
  cuenta_nombre: '',
  cantidad: 0,
  precio: 0,
  pago: 0,
  pago_operado: 0,
  porcentaje: 0,
  porcentaje_descuento: 0,
  descuento: 0,
  subtotal: 0,
  total_bruto: 0,
  base_impuesto: 0,
  base: 0,
  impuesto: 0,
  impuesto_operado: 0,
  impuesto_retencion: 0,
  total: 0,
  hora: 0,
  dias: 0,
  devengado: 0,
  deducion: 0,
  operacion: 0,
  base_cotizacion: 0,
  base_prestacion: 0,
  documento_afectado_id: undefined,
  documento_afectado_numero: '',
  documento_afectado_contacto_nombre_corto: '',
  contacto_id: undefined,
  contacto_nombre_corto: '',
  naturaleza: undefined,
  detalle: undefined,
  numero: undefined,
  concepto_id: undefined,
  concepto_nombre: '',
  tipo_registro: 'I',
  credito_id: undefined,
  grupo_id: 0,
  grupo_nombre: '',
  almacen_id: 0,
  almacen_nombre: '',
  impuestos: [],
  almacen: 1,
  codigo: '',
};
